### ISSUE TITLE
Concrete should not depend on specific SLF4J backends

### ISSUE THREAD

**Issue by reckart** [hltcoe/concrete#1]
Concrete should not depend on specific SLF4J backends. As a library, concrete should only depend on the SLF4J API, but not on any specific implementations such as LOG4J. The actual backend should be chosen by the user of the the library, i.e. the person that builds an application using concrete.

Having a re-usable library depend on a SLF4J backends introduces a high risk of ending up with multiple backends on the classpath when the library is being used within an application.

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/.../.m2/repository-ukp/org/apache/logging/log4j/log4j-slf4j-impl/2.5/log4j-slf4j-impl-2.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/.../.m2/repository-ukp/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```

Concretely affected (sorry!) are

* `concrete-safe` 4.10.0
* `concrete-util` 4.10.0
* maybe others ;)

**Comment by maxthomas** [comment]
thanks for reporting this!

would you mind closing this issue here and reposting it in the [concrete-java](https://github.com/hltcoe/concrete-java) library, as it is quite java specific?

**Comment by reckart** [comment]
Done: https://github.com/hltcoe/concrete-java/issues/6
